chore(notation): use a_o for total number of octets
gavofyork/graypaper pull request #174
Opened 2024-12-22 08:49 UTC by clearloop

I'd propose to use `a_o` instead of `a_l` for the concept of total number of octets,  the same notation `a_l` has been used for different concepts in 

- `9. Service Accounts`
  -  `a_\mathbf{l}` - lookup dictionaries ( Overview )
  - `a_l` - total number of octets in account footprint (`9.3 Account Footprint and Threshold Balance, formula (9.8)`)
- `D.2 merklization (D.2)`
  - `a_\mathbf{l}` - total number of octets
  - `a_\mathbf{l}` - lookup dictionary

we definitely can update `a_l` for the total number of octets in `D.2` but it makes it out of the format of `a_i` -> `a_\mathbf{i}`

## **why choosing `a_o`?**

in the same chapter 9.3:

- `a_i` for the number of <kbd>items</kbd> in storage
- `a_o` for the ~t~otal number of <kbd>octets</kbd> used in storage

2024-12-22 09:26 UTC, gavofyork requested changes

2024-12-22 09:26 UTC, gavofyork commented on text/accounts.tex
>      a_t \in \N_B &\equiv \mathsf{B}_S + \mathsf{B}_I \cdot a_i + \mathsf{B}_L \cdot a_l
All uses of l within the Graypaper must be updated. There is at least one other here.

2024-12-22 09:59 UTC, clearloop commented
verifying script

```
cd graypaper/text

# 1. find fi the previous a_l still exist
grep 'a_l' **/*.tex
grep -E '\mathbf\{a\}_l' **/*.tex

# 2. review the newly updated a_o
grep 'a_o' **/*.tex
# accounts.tex:    a_o \in \N_{2^{64}} &\equiv \sum\limits_{\,(h, z) \in \keys{a_\mathbf{l}}\,} 81 + z \\
# accounts.tex:    a_t \in \N_B &\equiv \mathsf{B}_S + \mathsf{B}_I \cdot a_i + \mathsf{B}_L \cdot a_o

grep -E '\mathbf\{a\}_o' **/*.tex
# merklization.tex:    \forall (s \mapsto \mathbf{a}) \in \delta: &&C(255, s) &\mapsto \mathbf{a}_c \concat \se_8(\mathbf{a}_b, \mathbf{a}_g, \mathbf{a}_m, \mathbf{a}_o) \concat \se_4(\mathbf{a}_i) \;, \\
```

2025-01-02 10:59 UTC, gavofyork commented
The script is only useful is the account term happens to be `a`. That's not necessarily the case. You should probably review all `_l` instances and check any which are account subscripts.

2025-01-02 11:01 UTC, gavofyork approved these changes

2025-01-02 11:01 UTC, merged